# Generated by Django 4.2.6 on 2023-10-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.FileField(blank=True, default=None, max_length=256, null=True, upload_to='profile_pictures'),
        ),
    ]
