# Generated by Django 4.2.6 on 2023-10-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.FileField(blank=True, default=None, null=True, upload_to='profile_pictures'),
        ),
    ]
